# Generated by Django 5.2.4 on 2025-09-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_List', '0003_task_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
